ЛР №3 на сдачу
avalon-dev-j110/laboratornaya-rabota-no3-Lena-Helen17 pull request #1
Opened 2020-04-12 10:17 UTC by Lena-Helen17

2020-04-12 16:45 UTC, konivex requested changes
Исправьте замечания в классе FibonacciInitializer.

2020-04-12 16:45 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
>  public class FibonacciInitializer implements Initializer {
При такой реализации экземпляр класса м.б. использован только один раз. Исправьте так, чтобы один и тот же экземпляр можно было использовать для инициализации нескольких массивов.

2020-04-12 16:45 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
> +        for (int i = 2; i < 20; i++) {
А если у массива длина будет не 20, а другая? Чем это кончится?

2020-04-12 16:45 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +		for (int text : array) {
Здесь и ниже: "text" неудачное имя для переменной типа int, он будет сбивать с толку читающий код.

2020-04-12 17:43 UTC, Lena-Helen17 commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
>  public class FibonacciInitializer implements Initializer {
Не понимаю про что это.

2020-04-12 17:47 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
>  public class FibonacciInitializer implements Initializer {
Ваш класс реализован так, что если я вызову FibonacciInitializer.initialize дважды, то второй раз метод заполнит массив неверными числами. Можете проверить это сами.
Исправьте класс так, чтобы массив заполнялся корректно и при повторных вызовах.

2020-04-12 18:02 UTC, konivex requested changes
Закончите исправление класса FibonacciInitializer.

2020-04-12 18:02 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
>  public class FibonacciInitializer implements Initializer {
Можно сделать ещё проще. Подумайте как.

2020-04-14 19:40 UTC, konivex requested changes
Исправление ещё одно замечание в коде класса `FibonacciInitializer`.

2020-04-14 19:40 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
>      public void initialize(int[] array) {
Метод будет выбрасывать исключение, если длина массива `array` будет меньше двух.
Исправьте метод, чтобы он работал корректно с массивами длины меньше двух.

2020-04-18 11:32 UTC, konivex requested changes
Исправьте замечания в методе `FibonacciInitializer.initialize`.

2020-04-18 11:32 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
> +        if (array.length > 2) {
Массив длиной в 2 элемента тоже может быть обработан этой веткой. Исправьте.

2020-04-18 11:32 UTC, konivex commented on src/ru/avalon/java/dev/j10/labs/initialization/FibonacciInitializer.java
> +        } else System.out.println("В массиве меньше 2 элементов или он пустой");
1. Выполнение метода не должно иметь сторонних эффектов в виде вывода чего-либо куда-либо, если это явно не требуется. Здесь не требуется.
1. Массив длиной в 1 элемент должен заполняться.

2020-04-18 13:51 UTC, konivex approved these changes
Зачтено.
Весь курс зачтён.

2020-04-27 08:38 UTC, merged